name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

inputs:
  searchPatterns:
    description: 'A comma separated list of patterns used to search for Markdown files to transform.'
    required: false
    default: '**/*.md'
  ignorePatterns:
    description: 'The list of patterns for files to exclude.'
    required: false
    default: 'node_modules/**'

runs:
  using: node20
  main: dist/index.js
