name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          hashnodeApiKey: ${{ secrets.HASHNODE_API_KEY }}
          mediumApiKey: ${{ secrets.MEDIUM_API_KEY }}
          devToApiKey: ${{ secrets.DEVTO_API_KEY }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
